version: "3.9"
services:
  backend:
    image: '#image'
    container_name: prostory
    restart: always
    ports:
      - "80:2026"
    environment:
      SPRING_PROFILES_ACTIVE: main
      SERVER_PORT: 2026
      POSTGRES_DB: prostory
      POSTGRES_USER: prostoryuser
      POSTGRES_PASSWORD: prostorypass
  database:
    image: postgres:15
    restart: always
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prostoryuser
      POSTGRES_PASSWORD: prostorypass
      POSTGRES_DB: prostory
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:

