version: '3.8'
services:
  db:
    image: postgres:15
    container_name: prostory_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: prostory
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: prostory_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/prostory