spring.datasource.url=jdbc:postgresql://database:5432/prostory
spring.datasource.username=prostoryuser
spring.datasource.password=prostorypass
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=a.aizada.a3@gmail.com
spring.mail.password=jfkxcylxxacclhch
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT
spring.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

# AWS
aws-access-key=????_access_key
aws-secret-key=????_secret_key
aws-region=eu-central-1

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true